[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/17GqTXQOxLSRLqd0DuNE24XVC20caWwpkXYJB6vwNwzA/edit?usp=sharing"

type = "service_account"
project_id = "precise-plane-481307-u2"
private_key_id = "dfcac0f97284f780eb7a3380d109a9fc09f9437b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxouZfiVIPsMan
BIj6L0RHtEDkd6duEIqwT3V1x/N7fw73jCK+VkLYGzJCQlDFr9x9x89UThnlr1Ml
TsWCOyGeREKMRJ7WCgQSt0DL/u4nY0xmAfbofgPTUvU7b1IZFbA0GkqE8YS+BGJr
EYULY8Ob9LwXQtjKJ2pkpYTaBXfRvrQV7SjoKlnaJBOlTHI/BzrPH77cAiq3RPXv
ItA5u20Ed36YqWgL81xZC55/B64VCyCHwA26+lwaSY6FC57IzzGYr+AWx7v4WzFs
w2sP5pQhaB6/eiCgLV46hTkYMgnMyaB5eTA+9IxjZeYmCxZmqEGLZRj3ieS0pdT8
3WAEBuu1AgMBAAECggEAAnI6Vu12rlWiXrFuy3c0KwKd9Cd7rEXZCxWFChKvVS+K
Prl0zwc0E3LIbeYo45gI4siKH+CVdbbE39omWSVEUMAi5HibcVog9TsFzulbUTqK
VktHoar+lX3qd5+QU10bmJQWG5+R0uYPjubmXKJKks67elyGzL3fNrSa0D/MBxzh
zNtW2lEV7PROURbGczJMAOT8JT5k0KZrIHOW1MLqmdm9Y5ZsilJ2+XHQuuBoVt0m
EVHDBYINJdEs0dfoZEr5qAFBtFgyVIVl+ABdunAZZyJtPngbEJlbJESn5wHbIadO
iE7JxMApZPZ/e4kLm5o2x7BIRbTTlrGzhJJYoXXeYQKBgQDmhr4pwjqxSKqy13+c
Gy0PKV2rFhUiUeHnFXm3EBv2KsBbIEOPtZnRk3R4uqeJMr8RzTyraZ9tIHfQ8wYU
HeUHLqQzWeR0HCIwXbq5Bj4pg91EjBSbWnEdQC+BvfzXkrIZFef7kuRiPWDGwIoy
W48EzdbRJnOmeCVwbZXF0+ecBQKBgQDFQ/mcG5mkTVS1paL8cRQfHMFbVOCtVHFy
KrmcrgUxtFFhNu0c6ZDprj+XCI5Rn+zEtAmZRUd1d2M3reW0l4WftjtpVzmaxJ1H
k2gUqfkFJFPbgbp3UK24FBAsB9/Gt+k9dsPRGQHMgavtmvb+PVs4g2N1oWeRoB/j
s8SjLZHP8QKBgQCRpip5+dTZdB8dtdhTijwS60DaOq6Jq5B+T2xChHQWOXalXKIz
JzsTVgXtzYjSv3RHTBP7/VUUPsJVC2cYyLaOriJiq3YTAj97rYyvIEmgM0dW6uaO
LTtwjsA1ShN5JJ9QCC41Hd8cTslZagcmwACBuYfzR0cks558BVDu1+7q/QKBgHTi
QhRthiwEZhz7eAd8OR/2OduT/0y0rEOpbTGZKxq4bT/c+8IV4veTd7pWJ33V9MTY
qJdYpW7EvtVPBLxsy5BGug1A0bESrt6qSRF1ZUfWrplx1Lq94zEfMjXktINalakF
piFPX/F9JBI1sAQU9ugVcelRKbzv0/VnnyvQ5IUBAoGABGF+z/kcD4ZwJ1kZCOPy
SPpAKQMqzhWaY3WeICkMYermOIbuYZ+hkA1XnKHR9LdKIZV3bjNQcozy8A45eo/y
NLm4NNcuHxQ98iyNzg0imj8QJZOF3ayqggqXFVjIcfLZ28dM0QP8s/GBf06QcvN/
q4KWqH89a4Gw65AeeS4cqPM=
-----END PRIVATE KEY-----"""
client_email = "yips-824@precise-plane-481307-u2.iam.gserviceaccount.com"
client_id = "112715743613271459523"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/yips-824%40precise-plane-481307-u2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"